name: Release to PyPI

on:
  push:
    branches: [ "main" ]

jobs:
  build-n-publish:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install pypa/setuptools
      run: >-
        python -m
        pip install wheel
    - name: Build a binary wheel
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}